<?php

/**
 * @file
 * Contains popular_cars_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function popular_cars_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the popular_cars_block module.
    case 'help.page.popular_cars_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function popular_cars_block_theme ( $existing, $type, $theme, $path ) {
    return [
        'popular_cars_block' => array(
            'template'  => 'popular-cars-block',
            'variables' => [
                'content'  => [],
            ],
        ),
    ];
}
