<?php

/**
 * @file
 * Contains price_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function price_block_help ( $route_name, RouteMatchInterface $route_match ) {
	switch ( $route_name ) {
		// Main module help for the featured_block module.
		case 'help.page.featured_block':
			$output = '';
			$output .= '<h3>' . t( 'About' ) . '</h3>';
			$output .= '<p>' . t( 'Price Block' ) . '</p>';

			return $output;

		default:
	}
}

/**
 * Implements hook_theme().
 */
function price_block_theme ( $existing, $type, $theme, $path ) {
	return [
		'price_block' => array(
			'template'  => 'price-block',
			'variables' => [
				'content'  => [],
			],
		),
	];
}