<?php

/**
 * @file
 * Contains cars_city_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cars_city_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cars_city_block module.
    case 'help.page.cars_city_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function cars_city_block_theme ( $existing, $type, $theme, $path ) {
    return [
        'cars_city_block' => array(
            'template'  => 'cars_city-block',
            'variables' => [
                'content'  => [],
            ],
        ),
    ];
}
