<?php

/**
 * @file
 * Contains latest_cars_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function latest_cars_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the latest_cars_block module.
    case 'help.page.latest_cars_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function latest_cars_block_theme ( $existing, $type, $theme, $path ) {
    return [
        'latest_cars_block' => array(
            'template'  => 'latest-cars-block',
            'variables' => [
                'content'  => [],
            ],
        ),
    ];
}
