<?php

/**
 * @file
 * Contains form_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function form_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_module module.
    case 'help.page.form_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('module for custom form') . '</p>';
      return $output;

    default:
  }
}
